### ISSUE TITLE
io.njiwa classes not writing logs

### ISSUE THREAD

**Issue by gmlemus** [bagyenda/njiwa#10]
I wanted to ask for help.
I see that in io.njiwa.common.Utils there is a general logger declared on the platform:

`public final static org.apache.log4j.Logger lg =
            org.apache.log4j.Logger.getLogger(InitialiserServlet.class.getName());`

I can see references of this logger in different classes.
however as when executing the war inside of a wildfly 11, there is no log activity for the lg variable.

I have tried to modify the logging subsystem of the standalone.xml

`            <logger category="io.njiwa.common">
                <level name="DEBUG"/>
            </logger>
            <logger category="Utils">
                <level name="DEBUG"/>
            </logger>
`

i tested updating the log4j library as well testing with logback with no success.
The only type of loggin i see is related to other wildfly executing libraries:

`04:25:25,215 DEBUG [org.jboss.as.controller.management-operation] (Controller Boot Thread) Committed transaction for transactions subsystem MODEL stage boot operations
04:25:25,215 DEBUG [org.jboss.as.controller.management-operation] (Controller Boot Thread) Committed transaction for undertow subsystem MODEL stage boot operations
04:25:25,215 DEBUG [org.jboss.as.controller.management-operation] (Controller Boot Thread) Committed transaction for webservices subsystem MODEL stage boot operations
04:25:25,215 DEBUG [org.jboss.as.controller.management-operation] (Controller Boot Thread) Committed transaction for weld subsystem MODEL stage boot operations
04:25:25,215 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 43) WFLYSRV0010: Deployed "njiwa-0.7.war" (runtime-name : "njiwa-0.7.war")
04:25:25,221 DEBUG [org.jboss.as.controller.management-operation] (Controller Boot Thread) Committed transaction for logging subsystem RUNTIME stage boot operations
04:25:25,222 DEBUG [org.jboss.as.controller.management-operation] (Controller Boot Thread) Committed transaction for batch-jberet subsystem RUNTIME stage boot operations
04:25:25,222 DEBUG [org.jboss.as.controller.management-operation] (Controller Boot Thread) Committed transaction for bean-validation subsystem RUNTIME stage boot operations
04:25:25,222 DEBUG [org.jboss.as.controller.management-operation] (Controller Boot Thread) Committed transaction for core-management subsystem RUNTIME stage boot operations
04:25:25,222 DEBUG [org.jboss.as.controller.management-operation] (Controller Boot Thread) Committed transaction for datasources subsystem RUNTIME stage boot operations
04:25:25,222 DEBUG [org.jboss.as.controller.management-operation] (Controller Boot Thread) Committed transaction for deployment-scanner subsystem RUNTIME stage boot operations`

could you please help me to understand if i am missing something.

**Comment by kitandara** [comment]
Should be fixed now. Please test and let me know
