### ISSUE TITLE
Injection is empty

### ISSUE THREAD

**Issue by kaerCreate** [bagyenda/njiwa#2]
When the client enables the server, the server's injection is empty.
eg:
        @Inject
          PersistenceUtility po;    //NULL
         @PersistenceContext
          private EntityManager em;  //NULL.

so,What should I do?

**Comment by kitandara** [comment]
Not sure I understand the question. What exactly are you trying to do?

**Comment by kaerCreate** [comment]
I wrote a client main function, the main code is

        QName  qn = new QName("http://namespaces.gsma.org/esim-messaging/1","SMSR");
        Service  ES3service = Service.create(new URL("https://localhost:8443/njiwa-0.7/ES3?wsdl"),qn);
        ES3 port = ES3service.getPort(ES3.class);
       .........
        GetEISResponse eis = port.getEIS(........);

But at ES3impl on the server side, the method getEis throws a null pointer exception because the Po is null;
   ES3Impl  Line157
        io.njiwa.sr.ws.types.Eis eis = CommonImpl.getEIS(po, eid, RpaEntity.Type.SMDP, sender, st);

**Comment by kitandara** [comment]
That's odd. There should be something in the log. This error means Wildlfly failed to inject dependencies into the classes...
