### ISSUE TITLE
org.apache.xerces.dom.ElementNSImpl cannot be cast to ...

### ISSUE THREAD

**Issue by quentinEvainTown** [bagyenda/njiwa#4]
when I try to call ES1.RegisterEIS,

 I get an exception "org.apache.xerces.dom.ElementNSImpl cannot be cast to io.nijiwa.sr.ws.types.EIS.SecurityDomain.KeySet", 

![code](https://user-images.githubusercontent.com/50440486/82113627-1150a400-978a-11ea-8634-3f6cac3070e2.png)

can you give some help, thanks

**Comment by kitandara** [comment]
Hi,
 Can you post a copy of the RegisterEIS XML.

**Comment by quentinEvainTown** [comment]
> 
> 
> Hi,
> Can you post a copy of the RegisterEIS XML.


[registerEIS.txt](https://github.com/bagyenda/njiwa/files/4649421/registerEIS.txt)
this is my RegisterEISxml,  please kindly check it

**Comment by kitandara** [comment]
Try pulling the repo again and this time change <KeyComponents> to <KeyComponent>

**Comment by quentinEvainTown** [comment]
it works now, thanks very much!

**Comment by quentinEvainTown** [comment]
Hi,
     Sorry for asking for help again, 
     
     I found  when we use @XmlAnyElement with List<Object> has the same problem , like ,
              List<KeySet> / List<ProfileInfo> / List<Certificate> / List<Pol2RuleType> ..
     we will get an exception "org.apache.xerces.dom.ElementNSImpl cannot be cast to ...

     I add (lax = true)  behind "@XmlAnyElement" as somebody told , but don't work.

**Comment by kitandara** [comment]
Could you try with the latest commits and let me know? I believe the @XmlAnyElement was the wrong kind of decorator

**Comment by quentinEvainTown** [comment]
Yes, i use the latest commits.

Already resolve this issue, just replace " @XmlAnyElement" with 
"@XmlElements(value = { @XmlElement(name = "KeySet", type = KeySet.class) })"  ,

Thanks for your advice!
