### ISSUE TITLE
Pre requisite missing in documentation?

### ISSUE THREAD

**Issue by gmlemus** [bagyenda/njiwa#7]
HI again:

I think there is a pre requisite missing based on the documentation in order to interact properly with at least the WSDL interface and based on the GSMA standard.
 The container need a SSL configured, all HTTP methods are redirected to HTTPS.
My question is that, can it be done at least for a review WSDL test with a non signed certificate? Can i follow the standard process or should i do something extra?

Please if you can help me on advice.

Thank you!!

**Comment by kitandara** [comment]
Yes you can  use a self-signed certificate
